### ISSUE TITLE
工作流无法RUN

### ISSUE THREAD

**Issue by searchingshi** [atom-im/hkpr#1]
您好，我导入了这段代码，但是工作流无法RUN。点了RUN之后还是提示有trigger。然后显示没有运行工作流。
麻烦帮忙看看谢谢。
his workflow has a workflow_dispatch event trigger.
GitHub Actions
This workflow has no runs yet.

**Comment by atom-im** [comment]
我也尝试重新导入了代码，并执行Run Workflow，一开始也遇到了你提到的问题。我进入Settings>Actions>General里面，查看了一下，但是没有做任何改动，回来到Actions页面又重新运行了一下，发现居然又可以了。

我直接在当前这个hkpr的Actions页面也运行了一下，发现运行的所需的时间远超预期，本来几秒钟就能执行完的操作花费了5-10分钟来运行。

或许你可以再试试重新运行一下，然后刷新页面看看有没有成功运行。记得也要设置一下REFERENCE和BIRTHDAY这两个参数。

**Comment by atom-im** [comment]
如果你会命令行操作，可以直接下载里面的脚本，直接linux/macos本地执行：
```
./hkpr.sh "RNVE-1234567-24(3)" "23-01-1990"
```
然后cronjob里面设置每天晚上8-11点查一下就行。

**Comment by searchingshi** [comment]
嗯，我已经搬到GCP上的instance里去跑了。GITHUB真不靠谱，谢谢。
PS: 小红书上问你的人也是我。


atom-im ***@***.***> 于2024年10月30日周三 17:35写道：

**Comment by searchingshi** [comment]
![image](https://github.com/user-attachments/assets/14c66d5f-b97d-4d4c-85a3-a180c0b646cf)
我没管他，吃了个饭回来一看，居然跑起来了，这可真神了。。。
